import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar";
import Template from "./components/RootLayout";
import { NavigationProvider } from "./utils/navigationContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://use.typekit.net/iqd6buu.css"
        />
      </head>
      <body className={inter.className}>
        <NavigationProvider>
          <Template>{children}</Template>
        </NavigationProvider>
      </body>
    </html>
  );
}
